// Code generated by go-gen-proxy; DO NOT EDIT.
package greeter

import (
	"fmt"
	"github.com/eiiches/go-gen-proxy/pkg/handler"
)

type GreeterProxy struct {
	Handler handler.InvocationHandler
}

func (this *GreeterProxy) SayHello(arg0 string) (string, error) {
	args := []interface{}{
		arg0,
	}

	rets := this.Handler.Invoke("SayHello", args)

	ret0, ok := rets[0].(string)
	if rets[0] != nil && !ok {
		panic(fmt.Sprintf("%+v is not a valid string value", rets[0]))
	}
	ret1, ok := rets[1].(error)
	if rets[1] != nil && !ok {
		panic(fmt.Sprintf("%+v is not a valid error value", rets[1]))
	}

	return ret0, ret1
}
